import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: ["typescript", "unicorn", "oxc", "import", "promise", "node", "vitest"],
  options: { typeAware: true },
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "warn",
  },
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
    { name: "ts-slop", specifier: "./tools/oxlint/ts-slop/index.ts" },
  ],
  rules: {
    "no-debugger": "error",
    "eslint/no-await-in-loop": "off",
    "eslint/no-underscore-dangle": "off",
    "eslint/no-control-regex": "off",
    "eslint/no-shadow": "off",
    "promise/always-return": "off",
    "oxc/no-map-spread": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/no-array-reverse": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-useless-spread": "off",
    "vitest/expect-expect": "off",
    "vitest/no-conditional-expect": "off",
    "vitest/require-mock-type-parameters": "off",
    "vitest/valid-expect": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/consistent-return": "off",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-condition": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/unbound-method": "off",
    "typescript/await-thenable": "off",
    "typescript/no-useless-default-assignment": "off",
    "typescript/require-array-sort-compare": "off",
    "typescript/consistent-type-imports": "error",
    "typescript/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      },
    ],
    "unicorn/prefer-module": "error",
    "unicorn/switch-case-braces": "error",
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-widen-then-assert": "error",
    "typescript/no-explicit-any": "error",
    "typescript/ban-ts-comment": "error",
    "eslint/no-useless-catch": "error",
    "ts-slop/no-dual-key-access": "error",
    "ts-slop/no-identity-passthrough": "error",
    "ts-slop/no-non-null-assertion-chain": "error",
    "ts-slop/no-reduce-as-map": "error",
    "ts-slop/no-redundant-boolean-if": "error",
    "ts-slop/no-sort-for-extremum": "error",
    "ts-slop/no-string-concat-in-reduce": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-misused-promises": "error",
    "typescript/return-await": ["error", "error-handling-correctness-only"],
    "typescript/only-throw-error": "error",
    "eslint/preserve-caught-error": "error",
    "eslint/no-useless-assignment": "error",
  },
  env: {
    builtin: true,
    node: true,
  },
  ignorePatterns: [
    ".pi/**",
    ".agents/**",
    ".tmp/**",
    "**/.tmp/**",
    "**/node_modules/**",
    "**/dist/**",
    "**/__fixtures__/**",
    "**/fixtures/**",
    "tools/oxlint/anti-slop/**",
    "tools/oxlint/ts-slop/**",
    "src/extensions/pi-agent-search/plugins/pi-agent-search-semantic/qmd/**",
  ],
});
