import type { ToolRecipe } from "pi-agent-doctor/api/catalog";

/**
LSP recipes owned by the LSP plugin.
*/
export const LSP_RECIPES: readonly ToolRecipe[] = [
  recipe(
    "clangd",
    ["c", "cpp"],
    ["clangd"],
    [".clangd", "compile_commands.json", "CMakeLists.txt"],
    { c: [".c", ".h"], cpp: [".cc", ".cpp", ".cxx", ".hh", ".hpp", ".hxx"] },
    ["clangd"],
    "https://clangd.llvm.org/",
  ),
  recipe(
    "typescript-language-server",
    ["javascript", "typescript"],
    ["typescript-language-server"],
    ["tsconfig.json", "jsconfig.json", "package.json"],
    { javascript: [".js", ".jsx", ".mjs", ".cjs"], typescript: [".ts", ".tsx", ".mts", ".cts"] },
    ["typescript-language-server", "--stdio"],
    "https://github.com/typescript-language-server/typescript-language-server",
    ["typescript-language-server"],
  ),
  recipe(
    "basedpyright",
    ["python"],
    ["basedpyright-langserver", "pyright-langserver"],
    ["pyproject.toml", "pyrightconfig.json"],
    { python: [".py", ".pyi"] },
    ["basedpyright-langserver", "--stdio"],
    "https://docs.basedpyright.com/",
    ["basedpyright"],
  ),
  recipe(
    "gopls",
    ["go"],
    ["gopls"],
    ["go.mod", "go.work"],
    { go: [".go"] },
    ["gopls"],
    "https://go.dev/gopls/",
  ),
  recipe(
    "rust-analyzer",
    ["rust"],
    ["rust-analyzer"],
    ["Cargo.toml", "rust-project.json"],
    { rust: [".rs"] },
    ["rust-analyzer"],
    "https://rust-analyzer.github.io/",
  ),
  recipe(
    "csharp-ls",
    ["csharp"],
    ["csharp-ls"],
    [".sln", ".csproj"],
    { csharp: [".cs"] },
    ["csharp-ls"],
    "https://github.com/razzmatazz/csharp-language-server",
  ),
  recipe(
    "jdtls",
    ["java"],
    ["jdtls"],
    ["pom.xml", "build.gradle", ".project"],
    { java: [".java"] },
    ["jdtls"],
    "https://projects.eclipse.org/projects/eclipse.jdt.ls",
  ),
  recipe(
    "kotlin-language-server",
    ["kotlin"],
    ["kotlin-language-server"],
    ["build.gradle.kts", "pom.xml"],
    { kotlin: [".kt", ".kts"] },
    ["kotlin-language-server"],
    "https://github.com/fwcd/kotlin-language-server",
  ),
  recipe(
    "solargraph",
    ["ruby"],
    ["solargraph"],
    ["Gemfile", ".solargraph.yml"],
    { ruby: [".rb", ".rake"] },
    ["solargraph", "stdio"],
    "https://solargraph.org/",
  ),
  recipe(
    "intelephense",
    ["php"],
    ["intelephense"],
    ["composer.json"],
    { php: [".php"] },
    ["intelephense", "--stdio"],
    "https://intelephense.com/",
  ),
  recipe(
    "sourcekit-lsp",
    ["swift"],
    ["sourcekit-lsp"],
    ["Package.swift"],
    { swift: [".swift"] },
    ["sourcekit-lsp"],
    "https://github.com/swiftlang/sourcekit-lsp",
  ),
  recipe(
    "lua-language-server",
    ["lua"],
    ["lua-language-server"],
    [".luarc.json", ".luarc.jsonc"],
    { lua: [".lua"] },
    ["lua-language-server"],
    "https://luals.github.io/",
  ),
  recipe(
    "bash-language-server",
    ["shell"],
    ["bash-language-server"],
    [".shellcheckrc"],
    { shell: [".sh", ".bash"] },
    ["bash-language-server", "start"],
    "https://github.com/bash-lsp/bash-language-server",
  ),
  recipe(
    "vscode-css-language-server",
    ["css"],
    ["vscode-css-language-server"],
    ["package.json"],
    { css: [".css", ".scss", ".less"] },
    ["vscode-css-language-server", "--stdio"],
    "https://github.com/microsoft/vscode-css-languageservice",
  ),
  recipe(
    "vscode-html-language-server",
    ["html"],
    ["vscode-html-language-server"],
    ["package.json"],
    { html: [".html", ".htm"] },
    ["vscode-html-language-server", "--stdio"],
    "https://github.com/microsoft/vscode-html-languageservice",
  ),
  recipe(
    "yaml-language-server",
    ["yaml"],
    ["yaml-language-server"],
    [".yamllint", "package.json"],
    { yaml: [".yaml", ".yml"] },
    ["yaml-language-server", "--stdio"],
    "https://github.com/redhat-developer/yaml-language-server",
  ),
  recipe(
    "taplo-lsp",
    ["toml"],
    ["taplo"],
    ["taplo.toml"],
    { toml: [".toml"] },
    ["taplo", "lsp", "stdio"],
    "https://taplo.tamasfe.dev/",
  ),
  recipe(
    "marksman",
    ["markdown"],
    ["marksman"],
    [".marksman.toml"],
    { markdown: [".md", ".mdx"] },
    ["marksman", "server"],
    "https://github.com/artempyanykh/marksman",
  ),
  recipe(
    "terraform-ls",
    ["terraform"],
    ["terraform-ls"],
    [".terraform.lock.hcl"],
    { terraform: [".tf", ".tfvars"] },
    ["terraform-ls", "serve"],
    "https://github.com/hashicorp/terraform-ls",
  ),
  recipe(
    "cmake-language-server",
    ["cmake"],
    ["cmake-language-server"],
    ["CMakeLists.txt"],
    { cmake: [".cmake"] },
    ["cmake-language-server"],
    "https://github.com/regen100/cmake-language-server",
  ),
  recipe(
    "vscode-json-language-server",
    ["json"],
    ["vscode-json-language-server"],
    ["package.json"],
    { json: [".json", ".jsonc"] },
    ["vscode-json-language-server", "--stdio"],
    "https://github.com/microsoft/vscode-json-languageservice",
  ),
  recipe(
    "lemminx",
    ["xml"],
    ["lemminx"],
    [".lemminx.json"],
    { xml: [".xml", ".xsd", ".xsl"] },
    ["lemminx"],
    "https://github.com/eclipse-lemminx/lemminx",
  ),
  recipe(
    "sqls",
    ["sql"],
    ["sqls"],
    [".sqls.yml"],
    { sql: [".sql"] },
    ["sqls"],
    "https://github.com/sqls-server/sqls",
  ),
  recipe(
    "docker-langserver",
    ["dockerfile"],
    ["docker-langserver"],
    ["Dockerfile"],
    { dockerfile: [".dockerfile"] },
    ["docker-langserver", "--stdio"],
    "https://github.com/rcjsuen/dockerfile-language-server-nodejs",
  ),
];

function recipe(
  id: string,
  languages: readonly string[],
  executables: readonly string[],
  rootMarkers: readonly string[],
  languageIds: Readonly<Record<string, readonly string[]>>,
  command: readonly string[],
  documentation: string,
  dependencies?: readonly string[],
): ToolRecipe {
  return {
    id,
    name: id,
    kind: "lsp",
    languages,
    executables,
    configFiles: rootMarkers,
    documentation,
    ...(dependencies && { dependencies }),
    lsp: { command, rootMarkers, languageIds },
  };
}
