import type { ToolRecipe } from "pi-agent-doctor/api/catalog";

/**
LSP recipes owned by the LSP plugin.
*/
export const LSP_RECIPES: readonly ToolRecipe[] = [
  {
    id: "vue-typescript-language-server",
    name: "vue-typescript-language-server",
    kind: "lsp",
    languages: ["vue"],
    executables: ["typescript-language-server"],
    dependencies: ["typescript-language-server", "@vue/typescript-plugin"],
    configFiles: ["tsconfig.json"],
    documentation: "https://github.com/vuejs/language-tools/tree/master/packages/typescript-plugin",
    lsp: {
      command: ["typescript-language-server", "--stdio"],
      rootMarkers: ["tsconfig.json", "package.json"],
      languageIds: { vue: [".vue"] },
      initializationOptions: {
        plugins: [
          {
            name: "@vue/typescript-plugin",
            location: "{project}/node_modules/@vue/typescript-plugin",
            languages: ["vue"],
          },
        ],
      },
    },
  },
  recipe(
    "elixir-ls",
    ["elixir"],
    ["elixir-ls"],
    ["mix.exs"],
    { elixir: [".ex", ".exs"] },
    ["elixir-ls"],
    "https://github.com/elixir-lsp/elixir-ls",
    undefined,
    undefined,
    { elixirLS: { mcpEnabled: false } },
  ),
  recipe(
    "metals",
    ["scala"],
    ["metals"],
    ["build.sbt", "project.scala", ".bsp"],
    { scala: [".scala", ".sc"] },
    ["metals"],
    "https://scalameta.org/metals/",
  ),
  {
    id: "angular-language-server",
    name: "angular-language-server",
    kind: "lsp",
    languages: ["typescript", "html"],
    executables: ["ngserver"],
    dependencies: ["@angular/language-server"],
    configFiles: ["angular.json"],
    documentation: "https://github.com/angular/vscode-ng-language-service",
    lsp: {
      command: ["ngserver", "--stdio", "--tsProbeLocations", ".", "--ngProbeLocations", "."],
      rootMarkers: ["angular.json"],
      requireRootMarker: true,
      languageIds: { typescript: [".ts"], html: [".html"] },
    },
  },
  recipe(
    "svelte-language-server",
    ["svelte"],
    ["svelteserver"],
    ["svelte.config.js", "package.json"],
    { svelte: [".svelte"] },
    ["svelteserver", "--stdio"],
    "https://github.com/sveltejs/language-tools/tree/master/packages/language-server",
    ["svelte-language-server"],
  ),
  recipe(
    "dart-language-server",
    ["dart"],
    ["dart"],
    ["pubspec.yaml", "analysis_options.yaml"],
    { dart: [".dart"] },
    ["dart", "language-server", "--protocol=lsp"],
    "https://dart.dev/tools/dart-language-server",
  ),
  recipe(
    "r-language-server",
    ["r"],
    ["Rscript"],
    ["DESCRIPTION", ".lintr", ".Rprofile"],
    { r: [".r"] },
    ["Rscript", "-e", "languageserver::run()"],
    "https://github.com/REditorSupport/languageserver",
  ),
  recipe(
    "zls",
    ["zig"],
    ["zls"],
    ["build.zig", "build.zig.zon", "zls.json"],
    { zig: [".zig", ".zon"] },
    ["zls"],
    "https://zigtools.org/zls/",
  ),
  recipe(
    "clangd",
    ["c", "cpp"],
    ["clangd"],
    [".clangd", "compile_commands.json", "CMakeLists.txt"],
    { c: [".c", ".h"], cpp: [".cc", ".cpp", ".cxx", ".hh", ".hpp", ".hxx"] },
    ["clangd"],
    "https://clangd.llvm.org/",
  ),
  recipe(
    "typescript-language-server",
    ["javascript", "typescript"],
    ["typescript-language-server"],
    ["tsconfig.json", "jsconfig.json", "package.json"],
    {
      javascript: [".js", ".mjs", ".cjs"],
      javascriptreact: [".jsx"],
      typescript: [".ts", ".mts", ".cts"],
      typescriptreact: [".tsx"],
    },
    ["typescript-language-server", "--stdio"],
    "https://github.com/typescript-language-server/typescript-language-server",
    ["typescript-language-server"],
  ),
  recipe(
    "basedpyright",
    ["python"],
    ["basedpyright-langserver", "pyright-langserver"],
    ["pyproject.toml", "pyrightconfig.json"],
    { python: [".py", ".pyi"] },
    ["basedpyright-langserver", "--stdio"],
    "https://docs.basedpyright.com/",
    ["basedpyright"],
  ),
  recipe(
    "gopls",
    ["go"],
    ["gopls"],
    ["go.mod", "go.work"],
    { go: [".go"] },
    ["gopls"],
    "https://go.dev/gopls/",
  ),
  recipe(
    "rust-analyzer",
    ["rust"],
    ["rust-analyzer"],
    ["Cargo.toml", "rust-project.json"],
    { rust: [".rs"] },
    ["rust-analyzer"],
    "https://rust-analyzer.github.io/",
  ),
  recipe(
    "csharp-ls",
    ["csharp"],
    ["csharp-ls"],
    [".sln", ".csproj"],
    { csharp: [".cs"] },
    ["csharp-ls"],
    "https://github.com/razzmatazz/csharp-language-server",
  ),
  recipe(
    "jdtls",
    ["java"],
    ["jdtls"],
    ["pom.xml", "build.gradle", ".project"],
    { java: [".java"] },
    ["jdtls"],
    "https://projects.eclipse.org/projects/eclipse.jdt.ls",
  ),
  recipe(
    "kotlin-language-server",
    ["kotlin"],
    ["kotlin-language-server"],
    ["build.gradle.kts", "pom.xml"],
    { kotlin: [".kt", ".kts"] },
    ["kotlin-language-server"],
    "https://github.com/fwcd/kotlin-language-server",
  ),
  recipe(
    "solargraph",
    ["ruby"],
    ["solargraph"],
    ["Gemfile", ".solargraph.yml"],
    { ruby: [".rb", ".rake"] },
    ["solargraph", "stdio"],
    "https://solargraph.org/",
  ),
  recipe(
    "intelephense",
    ["php"],
    ["intelephense"],
    ["composer.json"],
    { php: [".php"] },
    ["intelephense", "--stdio"],
    "https://intelephense.com/",
  ),
  recipe(
    "sourcekit-lsp",
    ["swift"],
    ["sourcekit-lsp"],
    ["Package.swift"],
    { swift: [".swift"] },
    ["sourcekit-lsp"],
    "https://github.com/swiftlang/sourcekit-lsp",
  ),
  recipe(
    "lua-language-server",
    ["lua"],
    ["lua-language-server"],
    [".luarc.json", ".luarc.jsonc"],
    { lua: [".lua"] },
    ["lua-language-server"],
    "https://luals.github.io/",
  ),
  recipe(
    "bash-language-server",
    ["shell"],
    ["bash-language-server"],
    [".shellcheckrc"],
    { shell: [".sh", ".bash"] },
    ["bash-language-server", "start"],
    "https://github.com/bash-lsp/bash-language-server",
  ),
  recipe(
    "vscode-css-language-server",
    ["css"],
    ["vscode-css-language-server"],
    ["package.json"],
    { css: [".css", ".scss", ".less"] },
    ["vscode-css-language-server", "--stdio"],
    "https://github.com/microsoft/vscode-css-languageservice",
    undefined,
    undefined,
    { css: {}, scss: {}, less: {} },
  ),
  recipe(
    "vscode-html-language-server",
    ["html"],
    ["vscode-html-language-server"],
    ["package.json"],
    { html: [".html", ".htm"] },
    ["vscode-html-language-server", "--stdio"],
    "https://github.com/microsoft/vscode-html-languageservice",
  ),
  recipe(
    "yaml-language-server",
    ["yaml"],
    ["yaml-language-server"],
    [".yamllint", "package.json"],
    { yaml: [".yaml", ".yml"] },
    ["yaml-language-server", "--stdio"],
    "https://github.com/redhat-developer/yaml-language-server",
  ),
  recipe(
    "taplo-lsp",
    ["toml"],
    ["taplo"],
    ["taplo.toml"],
    { toml: [".toml"] },
    ["taplo", "lsp", "stdio"],
    "https://taplo.tamasfe.dev/",
  ),
  recipe(
    "marksman",
    ["markdown"],
    ["marksman"],
    [".marksman.toml"],
    { markdown: [".md", ".mdx"] },
    ["marksman", "server"],
    "https://github.com/artempyanykh/marksman",
  ),
  recipe(
    "terraform-ls",
    ["terraform"],
    ["terraform-ls"],
    [".terraform.lock.hcl"],
    { terraform: [".tf", ".tfvars"] },
    ["terraform-ls", "serve"],
    "https://github.com/hashicorp/terraform-ls",
  ),
  recipe(
    "kotlin-lsp",
    ["kotlin"],
    ["intellij-server"],
    ["build.gradle.kts", "build.gradle", "pom.xml", "settings.gradle.kts"],
    { kotlin: [".kt", ".kts"] },
    ["intellij-server", "--stdio"],
    "https://github.com/Kotlin/kotlin-lsp",
  ),
  recipe(
    "julia-language-server",
    ["julia"],
    ["julia"],
    ["Project.toml", "JuliaProject.toml"],
    { julia: [".jl"] },
    ["julia", "--startup-file=no", "--history-file=no", "-e", "using LanguageServer; runserver()"],
    "https://github.com/julia-vscode/LanguageServer.jl",
  ),
  recipe(
    "powershell-editor-services",
    ["powershell"],
    ["pwsh"],
    ["PSScriptAnalyzerSettings.psd1"],
    { powershell: [".ps1", ".psm1", ".psd1"] },
    [
      "pwsh",
      "-NoProfile",
      "-NonInteractive",
      "-Command",
      '$ErrorActionPreference="Stop";Import-Module PowerShellEditorServices;$d=Join-Path (Get-Location) ".agents/tmp/powershell-lsp-$PID";[IO.Directory]::CreateDirectory($d)|Out-Null;Start-EditorServices -HostName Pi -HostProfileId Pi -HostVersion 1.0.0 -Stdio -LanguageServiceOnly -LogPath (Join-Path $d "server.log") -SessionDetailsPath (Join-Path $d "session.json")',
    ],
    "https://github.com/PowerShell/PowerShellEditorServices",
  ),
  recipe(
    "neocmakelsp",
    ["cmake"],
    ["neocmakelsp"],
    ["CMakeLists.txt", ".neocmake.toml", ".neocmakelint.toml"],
    { cmake: [".cmake"] },
    ["neocmakelsp", "stdio"],
    "https://github.com/neocmakelsp/neocmakelsp",

    undefined,
    { cmake: ["CMakeLists.txt"] },
  ),
  recipe(
    "vscode-json-language-server",
    ["json"],
    ["vscode-json-language-server"],
    ["package.json"],
    { json: [".json", ".jsonc"] },
    ["vscode-json-language-server", "--stdio"],
    "https://github.com/microsoft/vscode-json-languageservice",
  ),
  recipe(
    "lemminx",
    ["xml"],
    ["lemminx"],
    [".lemminx.json"],
    { xml: [".xml", ".xsd", ".xsl"] },
    ["lemminx"],
    "https://github.com/eclipse-lemminx/lemminx",
  ),
  recipe(
    "sqls",
    ["sql"],
    ["sqls"],
    [".sqls.yml"],
    { sql: [".sql"] },
    ["sqls"],
    "https://github.com/sqls-server/sqls",
  ),
  recipe(
    "docker-langserver",
    ["dockerfile"],
    ["docker-langserver"],
    ["Dockerfile"],
    { dockerfile: [".dockerfile"] },
    ["docker-langserver", "--stdio"],
    "https://github.com/rcjsuen/dockerfile-language-server-nodejs",

    undefined,
    { dockerfile: ["Dockerfile", "Containerfile"] },
  ),
];

function recipe(
  id: string,
  languages: readonly string[],
  executables: readonly string[],
  rootMarkers: readonly string[],
  languageIds: Readonly<Record<string, readonly string[]>>,
  command: readonly string[],
  documentation: string,
  dependencies?: readonly string[],
  fileNames?: Readonly<Record<string, readonly string[]>>,

  settings?: Readonly<Record<string, unknown>>,
): ToolRecipe {
  return {
    id,
    name: id,
    kind: "lsp",
    languages,
    executables,
    configFiles: rootMarkers,
    documentation,
    ...(dependencies && { dependencies }),
    lsp: {
      command,
      rootMarkers,
      languageIds,
      ...(fileNames && { fileNames }),
      ...(settings && { settings }),
    },
  };
}
