import type { ToolRecipe } from "pi-agent-doctor/api/catalog";
import type { DiagnosticFormat } from "pi-agent-ide/api/tool-config";

/**
Linter recipes owned by the lint plugin.
*/
export const LINTER_RECIPES: readonly ToolRecipe[] = [
  recipe(
    "dart-analyze",
    ["dart"],
    ["dart"],
    ["analysis_options.yaml", "pubspec.yaml"],
    [".dart"],
    ["dart", "analyze", "--format", "machine", "{file}"],
    "regex",
    "https://dart.dev/tools/dart-analyze",
    "^(?<severity>[^|]+)\\|[^|]+\\|(?<code>[^|]+)\\|(?<file>[^|]+)\\|(?<line>\\d+)\\|(?<column>\\d+)\\|\\d+\\|(?<message>.*)$",
    undefined,
    [0, 1, 2, 3],
  ),
  recipe(
    "zig-ast-check",
    ["zig"],
    ["zig"],
    ["build.zig", "build.zig.zon", "zls.json"],
    [".zig", ".zon"],
    ["zig", "ast-check", "{file}"],
    "gcc",
    "https://ziglang.org/documentation/master/",
  ),
  recipe(
    "lintr",
    ["r"],
    ["Rscript"],
    [".lintr", "DESCRIPTION"],
    [".r"],
    ["Rscript", "-e", "print(lintr::lint(commandArgs(TRUE)[1]))", "{file}"],
    "regex",
    "https://lintr.r-lib.org/",
    "^(?<file>.+?):(?<line>\\d+):(?<column>\\d+): (?<severity>[^:]+): \\[(?<code>[^\\]]+)\\] (?<message>.*)$",
  ),
  recipe(
    "clang-tidy",
    ["c", "cpp"],
    ["clang-tidy"],
    [".clang-tidy", "compile_commands.json"],
    [".c", ".h", ".cc", ".cpp", ".cxx", ".hh", ".hpp", ".hxx"],
    ["clang-tidy", "{file}"],
    "clang",
    "https://clang.llvm.org/extra/clang-tidy/",
  ),
  recipe(
    "eslint",
    ["javascript", "typescript", "vue", "svelte"],
    ["eslint"],
    [
      "eslint.config.js",
      "eslint.config.mjs",
      "eslint.config.cjs",
      "eslint.config.ts",
      "eslint.config.mts",
      "eslint.config.cts",
      ".eslintrc",
      ".eslintrc.json",
      ".eslintrc.js",
      ".eslintrc.cjs",
      ".eslintrc.yaml",
      ".eslintrc.yml",
    ],
    [".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts", ".vue", ".svelte"],
    ["eslint", "--format", "json", "{file}"],
    "eslint-json",
    "https://eslint.org/docs/latest/",
    undefined,
    ["eslint"],
  ),
  recipe(
    "oxlint",
    ["javascript", "typescript"],
    ["oxlint"],
    [".oxlintrc.json", ".oxlintrc.jsonc", "oxlint.config.ts", "oxlint.config.mts"],
    [".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts"],
    ["oxlint", "--format", "sarif", "{file}"],
    "sarif",
    "https://oxc.rs/docs/guide/usage/linter.html",
    undefined,
    ["oxlint"],
  ),
  recipe(
    "ruff",
    ["python"],
    ["ruff"],
    ["pyproject.toml", "ruff.toml", ".ruff.toml"],
    [".py", ".pyi"],
    ["ruff", "check", "--output-format", "concise", "{file}"],
    "regex",
    "https://docs.astral.sh/ruff/",
    "^(?<file>.+?):(?<line>\\d+):(?<column>\\d+): (?<code>\\S+) (?<message>.+)$",
    ["ruff"],
  ),
  recipe(
    "golangci-lint",
    ["go"],
    ["golangci-lint"],
    [".golangci.yml", ".golangci.yaml", "go.mod"],
    [".go"],
    [
      "golangci-lint",
      "run",
      "--output.text.path=",
      "--output.checkstyle.path=stdout",
      "--show-stats=false",
      "./...",
    ],
    "checkstyle",
    "https://golangci-lint.run/",
  ),
  recipe(
    "clippy",
    ["rust"],
    ["cargo"],
    ["Cargo.toml", "clippy.toml"],
    [".rs"],
    ["cargo", "clippy", "--message-format", "short"],
    "gcc",
    "https://doc.rust-lang.org/clippy/",
  ),
  recipe(
    "dotnet-format",
    ["csharp"],
    ["dotnet"],
    [".editorconfig", "global.json"],
    [".cs"],
    ["dotnet", "format", "--verify-no-changes", "--include", "{relativeFile}"],
    "regex",
    "https://learn.microsoft.com/dotnet/core/tools/dotnet-format",
    "^(?<file>.+)\\((?<line>\\d+),(?<column>\\d+)\\): (?<severity>error|warning) (?<code>[^:]+): (?<message>.*?)(?: \\[.*\\])?$",
    undefined,
    [0, 2],
  ),
  recipe(
    "checkstyle",
    ["java"],
    ["checkstyle"],
    ["checkstyle.xml", "pom.xml"],
    [".java"],
    ["checkstyle", "-c", "checkstyle.xml", "-f", "xml", "{file}"],
    "checkstyle",
    "https://checkstyle.org/",
  ),
  recipe(
    "detekt",
    ["kotlin"],
    ["detekt"],
    ["detekt.yml", "build.gradle.kts"],
    [".kt", ".kts"],
    ["detekt", "--input", "{file}", "--config", "detekt.yml"],
    "regex",
    "https://detekt.dev/",
    "^(?<file>.+?):(?<line>\\d+):(?<column>\\d+): (?<message>.*?) \\[(?<code>[^\\]]+)\\]$",
    undefined,
    [0, 2],
  ),
  recipe(
    "rubocop",
    ["ruby"],
    ["rubocop"],
    [".rubocop.yml", "Gemfile"],
    [".rb", ".rake"],
    ["rubocop", "--format", "clang", "{file}"],
    "regex",
    "https://docs.rubocop.org/",
    "^(?<file>.+?):(?<line>\\d+):(?<column>\\d+): (?<severity>[A-Z]): (?:\\[Correctable\\] )?(?<code>[^:]+): (?<message>.*)$",
  ),
  recipe(
    "phpcs",
    ["php"],
    ["phpcs"],
    ["phpcs.xml", "phpcs.xml.dist", "composer.json"],
    [".php"],
    ["phpcs", "--report=checkstyle", "{file}"],
    "checkstyle",
    "https://github.com/PHPCSStandards/PHP_CodeSniffer",
    undefined,
    undefined,
    [0, 1, 2, 3],
  ),
  recipe(
    "swiftlint",
    ["swift"],
    ["swiftlint"],
    [".swiftlint.yml", "Package.swift"],
    [".swift"],
    ["swiftlint", "lint", "--quiet", "--reporter", "checkstyle", "{file}"],
    "checkstyle",
    "https://github.com/realm/SwiftLint",
    undefined,
    undefined,
    [0, 2],
  ),
  recipe(
    "scalafix",
    ["scala"],
    ["scalafix"],
    [".scalafix.conf"],
    [".scala", ".sc"],
    ["scalafix", "--check", "--files", "{file}"],
    "gcc",
    "https://scalacenter.github.io/scalafix/",
    undefined,
    undefined,
    [0, 2, 64, 66],
  ),
  recipe(
    "credo",
    ["elixir"],
    ["mix"],
    ["mix.exs", ".credo.exs"],
    [".ex", ".exs"],
    ["mix", "credo", "--strict", "--format", "flycheck", "--files-included", "{file}"],
    "regex",
    "https://hexdocs.pm/credo/",
    "^(?<file>.+):(?<line>\\d+):(?<column>\\d+): (?<severity>[A-Z]): (?<message>.+)$",
    undefined,
    Array.from({ length: 32 }, (_value, index) => index),
  ),
  recipe(
    "psscriptanalyzer",
    ["powershell"],
    ["pwsh"],
    ["PSScriptAnalyzerSettings.psd1"],
    [".ps1", ".psm1", ".psd1"],
    [
      "pwsh",
      "-NoProfile",
      "-NonInteractive",
      "-CommandWithArgs",
      '$ErrorActionPreference="Stop";$options=@{};if(Test-Path -LiteralPath PSScriptAnalyzerSettings.psd1){$options.Settings="PSScriptAnalyzerSettings.psd1"};Invoke-ScriptAnalyzer -Path $args[0] @options | ForEach-Object {"$($_.ScriptPath):$($_.Line):$($_.Column): $($_.Severity): $($_.Message) [$($_.RuleName)]"}',
      "{file}",
    ],
    "regex",
    "https://learn.microsoft.com/powershell/module/psscriptanalyzer/invoke-scriptanalyzer",
    "^(?<file>.+):(?<line>\\d+):(?<column>\\d+): (?<severity>\\w+): (?<message>.+) \\[(?<code>[^\\]]+)\\]$",
    undefined,
    [0],
  ),
  recipe(
    "luacheck",
    ["lua"],
    ["luacheck"],
    [".luacheckrc"],
    [".lua"],
    ["luacheck", "--formatter", "plain", "--codes", "--no-color", "{file}"],
    "regex",
    "https://github.com/lunarmodules/luacheck",
    "^(?<file>.+):(?<line>\\d+):(?<column>\\d+): \\((?<code>(?<severity>[WE])\\d+)\\) (?<message>.+)$",
    undefined,
    [0, 1, 2],
  ),
  recipe(
    "shellcheck",
    ["shell"],
    ["shellcheck"],
    [".shellcheckrc"],
    [".sh", ".bash", ".zsh"],
    ["shellcheck", "-f", "gcc", "{file}"],
    "gcc",
    "https://www.shellcheck.net/",
  ),
  recipe(
    "stylelint",
    ["css"],
    ["stylelint"],
    ["stylelint.config.js", ".stylelintrc.json"],
    [".css", ".scss", ".sass", ".less"],
    ["stylelint", "--formatter", "compact", "{file}"],
    "regex",
    "https://stylelint.io/",
    "^(?<file>.+): line (?<line>\\d+), col (?<column>\\d+), (?<severity>error|warning) - (?<message>.+) \\((?<code>[^)]+)\\)$",
    ["stylelint"],
    [0, 2],
  ),
  recipe(
    "yamllint",
    ["yaml"],
    ["yamllint"],
    [".yamllint", ".yamllint.yml"],
    [".yaml", ".yml"],
    ["yamllint", "-f", "parsable", "{file}"],
    "regex",
    "https://yamllint.readthedocs.io/",
    "^(?<file>.+?):(?<line>\\d+):(?<column>\\d+): \\[(?<severity>[^\\]]+)\\] (?<message>.*?) \\((?<code>[^)]+)\\)$",
  ),
  recipe(
    "markdownlint",
    ["markdown"],
    ["markdownlint"],
    [".markdownlint.json", ".markdownlint.yaml"],
    [".md", ".mdx"],
    ["markdownlint", "{file}"],
    "regex",
    "https://github.com/DavidAnson/markdownlint",
    "^(?<file>.+?):(?<line>\\d+)(?::(?<column>\\d+))? (?<severity>error|warning) (?<code>MD\\d+)(?:/\\S+)? (?<message>.*)$",
  ),
  recipe(
    "sqlfluff",
    ["sql"],
    ["sqlfluff"],
    [".sqlfluff", "pyproject.toml"],
    [".sql"],
    ["sqlfluff", "lint", "--format", "sarif", "{file}"],
    "sarif",
    "https://docs.sqlfluff.com/",
  ),
  recipe(
    "hadolint",
    ["dockerfile"],
    ["hadolint"],
    [".hadolint.yaml"],
    [".dockerfile"],
    ["hadolint", "--format", "checkstyle", "{file}"],
    "checkstyle",
    "https://github.com/hadolint/hadolint",
    undefined,
    undefined,
    [0, 1],
    undefined,
    ["Dockerfile", "Containerfile"],
  ),
  recipe(
    "tflint",
    ["terraform"],
    ["tflint"],
    [".tflint.hcl"],
    [".tf"],
    ["tflint", "--format", "checkstyle"],
    "checkstyle",
    "https://github.com/terraform-linters/tflint",
    undefined,
    undefined,
    [0, 2],
  ),
  recipe(
    "cmake-lint",
    ["cmake"],
    ["cmake-lint"],
    [".cmake-format.py", "CMakeLists.txt"],
    [".cmake"],
    ["cmake-lint", "{file}"],
    "regex",
    "https://cmake-format.readthedocs.io/",
    "^(?<file>.+?):(?<line>\\d+),(?<column>\\d+): \\[(?<code>(?<severity>[A-Z])\\d+)\\] (?<message>.*)$",
    undefined,
    [0, 1],
    0,
    ["CMakeLists.txt"],
  ),
  recipe(
    "htmlhint",
    ["html"],
    ["htmlhint"],
    [".htmlhintrc"],
    [".html", ".htm"],
    ["htmlhint", "--format", "checkstyle", "--nocolor", "{file}"],
    "checkstyle",
    "https://htmlhint.com/",
  ),
  recipe(
    "jsonlint",
    ["json"],
    ["jsonlint"],
    [
      ".jsonlintrc",
      ".jsonlintrc.json",
      ".jsonlintrc.yaml",
      ".jsonlintrc.yml",
      ".jsonlintrc.js",
      ".jsonlintrc.cjs",
      "jsonlint.config.js",
      "jsonlint.config.cjs",
    ],
    [".json"],
    ["jsonlint", "-q", "{file}"],
    "regex",
    "https://github.com/prantlf/jsonlint",
    "^(?:Error: )?(?<message>Parse (?<severity>error) on line (?<line>\\d+)(?:, column (?<column>\\d+))?:[^\\n]*)$",

    ["@prantlf/jsonlint", "jsonlint"],
  ),
  recipe(
    "taplo-check",
    ["toml"],
    ["taplo"],
    ["taplo.toml"],
    [".toml"],
    ["taplo", "check", "--colors", "never", "{file}"],
    "regex",
    "https://taplo.tamasfe.dev/",
    "^(?<severity>error): (?<message>[^\\n]+)\\n\\s*┌─ (?<file>.+):(?<line>\\d+):(?<column>\\d+)",
  ),
  recipe(
    "xmllint",
    ["xml"],
    ["xmllint"],
    [".xmllintrc"],
    [".xml", ".xsd", ".xsl"],
    ["xmllint", "--noout", "{file}"],
    "regex",
    "https://gnome.pages.gitlab.gnome.org/libxml2/xmllint.html",
    "^(?<file>.+?):(?<line>\\d+): (?<severity>(?:parser |validity )?(?:error|warning)) : (?<message>.*)$",
    undefined,
    [0, 1, 2, 3, 4],
  ),
];

function recipe(
  id: string,
  languages: readonly string[],
  executables: readonly string[],
  configFiles: readonly string[],
  extensions: readonly string[],
  command: readonly string[],
  format: DiagnosticFormat,
  documentation: string,
  pattern?: string,
  dependencies?: readonly string[],
  successExitCodes: readonly number[] = [0, 1],

  columnBase?: 0 | 1,
  fileNames?: readonly string[],
): ToolRecipe {
  return {
    id,
    name: id,
    kind: "linter",
    languages,
    executables,
    configFiles,
    documentation,
    ...(dependencies && { dependencies }),
    linter: {
      extensions,
      ...(fileNames && { fileNames }),
      check: { command, successExitCodes },
      diagnostics: {
        format,
        ...(pattern && { pattern }),
        ...(columnBase !== undefined && { columnBase }),
      },
    },
  };
}
