import type { ToolRecipe } from "pi-agent-doctor/api/catalog";
import type { DiagnosticFormat } from "pi-agent-ide/api/tool-config";

/**
Linter recipes owned by the lint plugin.
*/
export const LINTER_RECIPES: readonly ToolRecipe[] = [
  recipe(
    "clang-tidy",
    ["c", "cpp"],
    ["clang-tidy"],
    [".clang-tidy", "compile_commands.json"],
    [".c", ".h", ".cc", ".cpp", ".cxx", ".hpp"],
    ["clang-tidy", "{file}"],
    "clang",
    "https://clang.llvm.org/extra/clang-tidy/",
  ),
  recipe(
    "eslint",
    ["javascript", "typescript"],
    ["eslint"],
    ["eslint.config.js", "eslint.config.mjs", ".eslintrc.json"],
    [".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx"],
    ["eslint", "--format", "json", "{file}"],
    "eslint-json",
    "https://eslint.org/docs/latest/",
    undefined,
    ["eslint"],
  ),
  recipe(
    "oxlint",
    ["javascript", "typescript"],
    ["oxlint"],
    [".oxlintrc.json", ".oxlintrc.jsonc", "oxlint.config.ts", "oxlint.config.mts"],
    [".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts"],
    ["oxlint", "--format", "sarif", "{file}"],
    "sarif",
    "https://oxc.rs/docs/guide/usage/linter.html",
    undefined,
    ["oxlint"],
  ),
  recipe(
    "ruff",
    ["python"],
    ["ruff"],
    ["pyproject.toml", "ruff.toml", ".ruff.toml"],
    [".py", ".pyi"],
    ["ruff", "check", "--output-format", "concise", "{file}"],
    "regex",
    "https://docs.astral.sh/ruff/",
    "^(?<file>.+?):(?<line>\\d+):(?<column>\\d+): (?<code>\\S+) (?<message>.+)$",
    ["ruff"],
  ),
  recipe(
    "golangci-lint",
    ["go"],
    ["golangci-lint"],
    [".golangci.yml", ".golangci.yaml", "go.mod"],
    [".go"],
    ["golangci-lint", "run", "{file}"],
    "gcc",
    "https://golangci-lint.run/",
  ),
  recipe(
    "clippy",
    ["rust"],
    ["cargo"],
    ["Cargo.toml", "clippy.toml"],
    [".rs"],
    ["cargo", "clippy", "--message-format", "short"],
    "gcc",
    "https://doc.rust-lang.org/clippy/",
  ),
  recipe(
    "dotnet-format",
    ["csharp"],
    ["dotnet"],
    [".editorconfig", "global.json"],
    [".cs"],
    ["dotnet", "format", "--verify-no-changes"],
    "gcc",
    "https://learn.microsoft.com/dotnet/core/tools/dotnet-format",
  ),
  recipe(
    "checkstyle",
    ["java"],
    ["checkstyle"],
    ["checkstyle.xml", "pom.xml"],
    [".java"],
    ["checkstyle", "-f", "xml", "{file}"],
    "checkstyle",
    "https://checkstyle.org/",
  ),
  recipe(
    "detekt",
    ["kotlin"],
    ["detekt"],
    ["detekt.yml", "build.gradle.kts"],
    [".kt", ".kts"],
    ["detekt", "--input", "{file}"],
    "gcc",
    "https://detekt.dev/",
  ),
  recipe(
    "rubocop",
    ["ruby"],
    ["rubocop"],
    [".rubocop.yml", "Gemfile"],
    [".rb", ".rake"],
    ["rubocop", "--format", "clang", "{file}"],
    "clang",
    "https://docs.rubocop.org/",
  ),
  recipe(
    "phpcs",
    ["php"],
    ["phpcs"],
    ["phpcs.xml", "phpcs.xml.dist", "composer.json"],
    [".php"],
    ["phpcs", "--report=emacs", "{file}"],
    "gcc",
    "https://github.com/PHPCSStandards/PHP_CodeSniffer",
  ),
  recipe(
    "swiftlint",
    ["swift"],
    ["swiftlint"],
    [".swiftlint.yml", "Package.swift"],
    [".swift"],
    ["swiftlint", "lint", "--path", "{file}"],
    "gcc",
    "https://github.com/realm/SwiftLint",
  ),
  recipe(
    "luacheck",
    ["lua"],
    ["luacheck"],
    [".luacheckrc"],
    [".lua"],
    ["luacheck", "--formatter", "plain", "{file}"],
    "gcc",
    "https://github.com/lunarmodules/luacheck",
  ),
  recipe(
    "shellcheck",
    ["shell"],
    ["shellcheck"],
    [".shellcheckrc"],
    [".sh", ".bash", ".zsh"],
    ["shellcheck", "-f", "gcc", "{file}"],
    "gcc",
    "https://www.shellcheck.net/",
  ),
  recipe(
    "stylelint",
    ["css"],
    ["stylelint"],
    ["stylelint.config.js", ".stylelintrc.json"],
    [".css", ".scss", ".sass", ".less"],
    ["stylelint", "--formatter", "compact", "{file}"],
    "gcc",
    "https://stylelint.io/",
    undefined,
    ["stylelint"],
  ),
  recipe(
    "yamllint",
    ["yaml"],
    ["yamllint"],
    [".yamllint", ".yamllint.yml"],
    [".yaml", ".yml"],
    ["yamllint", "-f", "parsable", "{file}"],
    "gcc",
    "https://yamllint.readthedocs.io/",
  ),
  recipe(
    "markdownlint",
    ["markdown"],
    ["markdownlint"],
    [".markdownlint.json", ".markdownlint.yaml"],
    [".md", ".mdx"],
    ["markdownlint", "{file}"],
    "gcc",
    "https://github.com/DavidAnson/markdownlint",
  ),
  recipe(
    "sqlfluff",
    ["sql"],
    ["sqlfluff"],
    [".sqlfluff", "pyproject.toml"],
    [".sql"],
    ["sqlfluff", "lint", "--format", "sarif", "{file}"],
    "sarif",
    "https://docs.sqlfluff.com/",
  ),
  recipe(
    "hadolint",
    ["dockerfile"],
    ["hadolint"],
    [".hadolint.yaml"],
    ["*"],
    ["hadolint", "--format", "tty", "{file}"],
    "gcc",
    "https://github.com/hadolint/hadolint",
  ),
  recipe(
    "tflint",
    ["terraform"],
    ["tflint"],
    [".tflint.hcl"],
    [".tf"],
    ["tflint", "--format", "compact"],
    "gcc",
    "https://github.com/terraform-linters/tflint",
  ),
  recipe(
    "cmake-lint",
    ["cmake"],
    ["cmake-lint"],
    [".cmake-format.py", "CMakeLists.txt"],
    [".cmake"],
    ["cmake-lint", "{file}"],
    "gcc",
    "https://cmake-format.readthedocs.io/",
  ),
  recipe(
    "htmlhint",
    ["html"],
    ["htmlhint"],
    [".htmlhintrc"],
    [".html", ".htm"],
    ["htmlhint", "--format", "unix", "{file}"],
    "gcc",
    "https://htmlhint.com/",
  ),
  recipe(
    "jsonlint",
    ["json"],
    ["jsonlint"],
    ["package.json"],
    [".json", ".jsonc"],
    ["jsonlint", "-q", "{file}"],
    "gcc",
    "https://github.com/zaach/jsonlint",
  ),
  recipe(
    "taplo-check",
    ["toml"],
    ["taplo"],
    ["taplo.toml"],
    [".toml"],
    ["taplo", "check", "{file}"],
    "gcc",
    "https://taplo.tamasfe.dev/",
  ),
  recipe(
    "xmllint",
    ["xml"],
    ["xmllint"],
    [".xmllintrc"],
    [".xml", ".xsd", ".xsl"],
    ["xmllint", "--noout", "{file}"],
    "gcc",
    "https://gnome.pages.gitlab.gnome.org/libxml2/xmllint.html",
  ),
];

function recipe(
  id: string,
  languages: readonly string[],
  executables: readonly string[],
  configFiles: readonly string[],
  extensions: readonly string[],
  command: readonly string[],
  format: DiagnosticFormat,
  documentation: string,
  pattern?: string,
  dependencies?: readonly string[],
): ToolRecipe {
  return {
    id,
    name: id,
    kind: "linter",
    languages,
    executables,
    configFiles,
    documentation,
    ...(dependencies && { dependencies }),
    linter: {
      extensions,
      check: { command, successExitCodes: [0, 1] },
      diagnostics: { format, ...(pattern && { pattern }) },
    },
  };
}
