import type { ToolRecipe } from "pi-agent-doctor/api/catalog";

const web = [
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".ts",
  ".tsx",
  ".mts",
  ".cts",
  ".json",
  ".jsonc",
  ".css",
  ".scss",
  ".html",
  ".md",
  ".yaml",
  ".yml",
  ".vue",
  ".svelte",
];

const oxfmtExtensions = [
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".ts",
  ".tsx",
  ".mts",
  ".cts",
  ".json",
  ".jsonc",
  ".css",
  ".scss",
  ".less",
  ".html",
  ".htm",
  ".md",
  ".markdown",
  ".mdx",
  ".yaml",
  ".yml",
  ".toml",
];

/**
Formatter recipes owned by the formatter plugin.
*/
export const FORMATTER_RECIPES: readonly ToolRecipe[] = [
  recipe(
    "dart-format",
    ["dart"],
    ["dart"],
    ["pubspec.yaml", "analysis_options.yaml"],
    [".dart"],
    ["dart", "format", "{file}"],
    "https://dart.dev/tools/dart-format",
  ),
  recipe(
    "zig-format",
    ["zig"],
    ["zig"],
    ["build.zig", "build.zig.zon", "zls.json"],
    [".zig", ".zon"],
    ["zig", "fmt", "{file}"],
    "https://ziglang.org/documentation/master/",
  ),
  recipe(
    "styler",
    ["r"],
    ["Rscript"],
    [".Rprofile", "DESCRIPTION"],
    [".r"],
    ["Rscript", "-e", "styler::style_file(commandArgs(TRUE)[1])", "{file}"],
    "https://styler.r-lib.org/",
  ),
  recipe(
    "clang-format",
    ["c", "cpp"],
    ["clang-format"],
    [".clang-format", "_clang-format"],
    [".c", ".h", ".cc", ".cpp", ".cxx", ".hh", ".hpp", ".hxx"],
    ["clang-format", "-i", "{file}"],
    "https://clang.llvm.org/docs/ClangFormat.html",
  ),
  recipe(
    "prettier",
    ["javascript", "typescript", "html", "css", "json", "yaml", "markdown", "vue", "svelte"],
    ["prettier"],
    [
      ".prettierrc",
      ".prettierrc.json",
      ".prettierrc.json5",
      ".prettierrc.yaml",
      ".prettierrc.yml",
      ".prettierrc.toml",
      ".prettierrc.js",
      ".prettierrc.cjs",
      ".prettierrc.mjs",
      "prettier.config.js",
      "prettier.config.cjs",
      "prettier.config.mjs",
      "prettier.config.ts",
      "prettier.config.mts",
      "prettier.config.cts",
    ],
    web,
    ["prettier", "--write", "{file}"],
    "https://prettier.io/docs/",
    ["prettier"],
    { "package.json": ["prettier"] },
  ),
  recipe(
    "biome",
    ["javascript", "typescript", "json", "css"],
    ["biome"],
    ["biome.json", "biome.jsonc"],
    [".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts", ".json", ".jsonc", ".css"],
    ["biome", "format", "--write", "{file}"],
    "https://biomejs.dev/",
    ["@biomejs/biome"],
  ),
  recipe(
    "oxfmt",
    ["javascript", "typescript", "json", "css", "html", "markdown", "yaml", "toml"],
    ["oxfmt"],
    [".oxfmtrc.json", ".oxfmtrc.jsonc", "oxfmt.config.ts", "oxfmt.config.mts"],
    oxfmtExtensions,
    ["oxfmt", "--write", "{file}"],
    "https://oxc.rs/docs/guide/usage/formatter.html",
    ["oxfmt"],
  ),
  recipe(
    "ruff-format",
    ["python"],
    ["ruff"],
    ["ruff.toml", ".ruff.toml"],
    [".py", ".pyi"],
    ["ruff", "format", "{file}"],
    "https://docs.astral.sh/ruff/formatter/",
    ["ruff"],
    { "pyproject.toml": ["tool.ruff"] },
  ),
  recipe(
    "black",
    ["python"],
    ["black"],
    [],
    [".py", ".pyi"],
    ["black", "--quiet", "{file}"],
    "https://black.readthedocs.io/",
    ["black"],
    { "pyproject.toml": ["tool.black"] },
  ),
  recipe(
    "gofmt",
    ["go"],
    ["gofmt"],
    ["go.mod"],
    [".go"],
    ["gofmt", "-w", "{file}"],
    "https://pkg.go.dev/cmd/gofmt",
  ),
  recipe(
    "goimports",
    ["go"],
    ["goimports"],
    ["go.mod"],
    [".go"],
    ["goimports", "-w", "{file}"],
    "https://pkg.go.dev/golang.org/x/tools/cmd/goimports",
  ),
  recipe(
    "rustfmt",
    ["rust"],
    ["rustfmt"],
    ["rustfmt.toml", ".rustfmt.toml", "Cargo.toml"],
    [".rs"],
    ["rustfmt", "{file}"],
    "https://github.com/rust-lang/rustfmt",
  ),
  recipe(
    "csharpier",
    ["csharp"],
    ["csharpier"],
    [".csharpierrc", ".csharpierrc.json", ".csharpierrc.yaml", ".csharpierrc.yml"],
    [".cs"],
    ["csharpier", "format", "{file}"],
    "https://csharpier.com/",
  ),
  recipe(
    "google-java-format",
    ["java"],
    ["google-java-format"],
    ["pom.xml", "build.gradle"],
    [".java"],
    ["google-java-format", "--replace", "{file}"],
    "https://github.com/google/google-java-format",
  ),
  recipe(
    "ktlint-format",
    ["kotlin"],
    ["ktlint"],
    [".editorconfig", "build.gradle.kts"],
    [".kt", ".kts"],
    ["ktlint", "-F", "{file}"],
    "https://pinterest.github.io/ktlint/",
  ),
  recipe(
    "rubocop-format",
    ["ruby"],
    ["rubocop"],
    [".rubocop.yml", "Gemfile"],
    [".rb", ".rake"],
    ["rubocop", "--fix-layout", "{file}"],
    "https://docs.rubocop.org/",
  ),
  recipe(
    "pint",
    ["php"],
    ["pint"],
    ["pint.json", "composer.json"],
    [".php"],
    ["pint", "{file}"],
    "https://laravel.com/docs/pint",
  ),
  recipe(
    "swift-format",
    ["swift"],
    ["swift-format"],
    [".swift-format", "Package.swift"],
    [".swift"],
    ["swift-format", "format", "--in-place", "{file}"],
    "https://github.com/swiftlang/swift-format",
  ),
  recipe(
    "stylua",
    ["lua"],
    ["stylua"],
    ["stylua.toml", ".stylua.toml"],
    [".lua"],
    ["stylua", "{file}"],
    "https://github.com/JohnnyMorganz/StyLua",
  ),
  recipe(
    "shfmt",
    ["shell"],
    ["shfmt"],
    [".editorconfig"],
    [".sh", ".bash", ".zsh"],
    ["shfmt", "-w", "{file}"],
    "https://github.com/mvdan/sh",
  ),
  recipe(
    "taplo",
    ["toml"],
    ["taplo"],
    ["taplo.toml"],
    [".toml"],
    ["taplo", "format", "{file}"],
    "https://taplo.tamasfe.dev/",
  ),
  recipe(
    "sqlfluff-format",
    ["sql"],
    ["sqlfluff"],
    [".sqlfluff", "pyproject.toml"],
    [".sql"],
    ["sqlfluff", "format", "{file}"],
    "https://docs.sqlfluff.com/",
  ),
  recipe(
    "terraform-fmt",
    ["terraform"],
    ["terraform"],
    [".terraform.lock.hcl"],
    [".tf", ".tfvars"],
    ["terraform", "fmt", "{file}"],
    "https://developer.hashicorp.com/terraform/cli/commands/fmt",
  ),
  recipe(
    "cmake-format",
    ["cmake"],
    ["cmake-format"],
    [".cmake-format.py", "CMakeLists.txt"],
    [".cmake"],
    ["cmake-format", "-i", "{file}"],
    "https://cmake-format.readthedocs.io/",
    undefined,
    undefined,
    ["CMakeLists.txt"],
  ),
  recipe(
    "xmlformat",
    ["xml"],
    ["xmlformat"],
    [".xmlformat.conf"],
    [".xml", ".xsd", ".xsl"],
    ["xmlformat", "--overwrite", "{file}"],
    "https://github.com/pamoller/xmlformatter",
  ),
  recipe(
    "mix-format",
    ["elixir"],
    ["mix"],
    ["mix.exs", ".formatter.exs"],
    [".ex", ".exs"],
    ["mix", "format", "{file}"],
    "https://hexdocs.pm/mix/Mix.Tasks.Format.html",
  ),
  recipe(
    "scalafmt",
    ["scala"],
    ["scalafmt"],
    [".scalafmt.conf"],
    [".scala", ".sc", ".sbt"],
    ["scalafmt", "{file}"],
    "https://scalameta.org/scalafmt/",
  ),
  recipe(
    "julia-format",
    ["julia"],
    ["julia"],
    [".JuliaFormatter.toml", "Project.toml"],
    [".jl"],
    [
      "julia",
      "--startup-file=no",
      "--history-file=no",
      "-e",
      "using JuliaFormatter; format_file(ARGS[1])",
      "{file}",
    ],
    "https://github.com/domluna/JuliaFormatter.jl",
  ),
  recipe(
    "powershell-format",
    ["powershell"],
    ["pwsh"],
    ["PSScriptAnalyzerSettings.psd1"],
    [".ps1", ".psm1", ".psd1"],
    [
      "pwsh",
      "-NoProfile",
      "-NonInteractive",
      "-CommandWithArgs",
      '$ErrorActionPreference="Stop";$p=$args[0];$options=@{};if(Test-Path -LiteralPath PSScriptAnalyzerSettings.psd1){$options.Settings="PSScriptAnalyzerSettings.psd1"};[IO.File]::WriteAllText($p,(Invoke-Formatter -ScriptDefinition ([IO.File]::ReadAllText($p)) @options))',
      "{file}",
    ],
    "https://learn.microsoft.com/powershell/module/psscriptanalyzer/invoke-formatter",
  ),
  recipe(
    "dockfmt",
    ["dockerfile"],
    ["dockfmt"],
    ["Dockerfile", "Containerfile"],
    [".dockerfile"],
    ["dockfmt", "fmt", "--write", "{file}"],
    "https://github.com/jessfraz/dockfmt",
    undefined,
    undefined,
    ["Dockerfile", "Containerfile"],
  ),
];

function recipe(
  id: string,
  languages: readonly string[],
  executables: readonly string[],
  configFiles: readonly string[],
  extensions: readonly string[],
  command: readonly string[],
  documentation: string,
  dependencies?: readonly string[],
  configSections?: Readonly<Record<string, readonly string[]>>,

  fileNames?: readonly string[],
): ToolRecipe {
  return {
    id,
    name: id,
    kind: "formatter",
    languages,
    executables,
    configFiles,
    documentation,
    ...(dependencies && { dependencies }),

    ...(configSections && { configSections }),
    formatter: {
      extensions,
      ...(fileNames && { fileNames }),
      run: { command },
      output: "in-place",
    },
  };
}
