import type { ToolRecipe } from "pi-agent-doctor/api/catalog";

const web = [
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".ts",
  ".tsx",
  ".json",
  ".jsonc",
  ".css",
  ".scss",
  ".html",
  ".md",
];

const oxfmtExtensions = [
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".ts",
  ".tsx",
  ".mts",
  ".cts",
  ".json",
  ".jsonc",
  ".css",
  ".scss",
  ".less",
  ".html",
  ".htm",
  ".md",
  ".markdown",
  ".mdx",
  ".yaml",
  ".yml",
  ".toml",
];

/**
Formatter recipes owned by the formatter plugin.
*/
export const FORMATTER_RECIPES: readonly ToolRecipe[] = [
  recipe(
    "clang-format",
    ["c", "cpp"],
    ["clang-format"],
    [".clang-format", "_clang-format"],
    [".c", ".h", ".cc", ".cpp", ".cxx", ".hh", ".hpp", ".hxx"],
    ["clang-format", "-i", "{file}"],
    "https://clang.llvm.org/docs/ClangFormat.html",
  ),
  recipe(
    "prettier",
    ["javascript", "typescript", "html", "css", "json", "yaml", "markdown"],
    ["prettier"],
    [".prettierrc", ".prettierrc.json", "prettier.config.js"],
    web,
    ["prettier", "--write", "{file}"],
    "https://prettier.io/docs/",
    ["prettier"],
  ),
  recipe(
    "biome",
    ["javascript", "typescript", "json", "css"],
    ["biome"],
    ["biome.json", "biome.jsonc"],
    web,
    ["biome", "format", "--write", "{file}"],
    "https://biomejs.dev/",
    ["@biomejs/biome"],
  ),
  recipe(
    "oxfmt",
    ["javascript", "typescript", "json", "css", "html", "markdown", "yaml", "toml"],
    ["oxfmt"],
    [".oxfmtrc.json", ".oxfmtrc.jsonc", "oxfmt.config.ts", "oxfmt.config.mts"],
    oxfmtExtensions,
    ["oxfmt", "--write", "{file}"],
    "https://oxc.rs/docs/guide/usage/formatter.html",
    ["oxfmt"],
  ),
  recipe(
    "ruff-format",
    ["python"],
    ["ruff"],
    ["pyproject.toml", "ruff.toml", ".ruff.toml"],
    [".py", ".pyi"],
    ["ruff", "format", "{file}"],
    "https://docs.astral.sh/ruff/formatter/",
    ["ruff"],
  ),
  recipe(
    "black",
    ["python"],
    ["black"],
    ["pyproject.toml"],
    [".py", ".pyi"],
    ["black", "--quiet", "{file}"],
    "https://black.readthedocs.io/",
    ["black"],
  ),
  recipe(
    "gofmt",
    ["go"],
    ["gofmt"],
    ["go.mod"],
    [".go"],
    ["gofmt", "-w", "{file}"],
    "https://pkg.go.dev/cmd/gofmt",
  ),
  recipe(
    "goimports",
    ["go"],
    ["goimports"],
    ["go.mod"],
    [".go"],
    ["goimports", "-w", "{file}"],
    "https://pkg.go.dev/golang.org/x/tools/cmd/goimports",
  ),
  recipe(
    "rustfmt",
    ["rust"],
    ["rustfmt"],
    ["rustfmt.toml", ".rustfmt.toml", "Cargo.toml"],
    [".rs"],
    ["rustfmt", "{file}"],
    "https://github.com/rust-lang/rustfmt",
  ),
  recipe(
    "csharpier",
    ["csharp"],
    ["dotnet-csharpier", "csharpier"],
    [".csharpierrc", ".csharpierrc.json"],
    [".cs"],
    ["dotnet-csharpier", "format", "{file}"],
    "https://csharpier.com/",
  ),
  recipe(
    "google-java-format",
    ["java"],
    ["google-java-format"],
    ["pom.xml", "build.gradle"],
    [".java"],
    ["google-java-format", "--replace", "{file}"],
    "https://github.com/google/google-java-format",
  ),
  recipe(
    "ktlint-format",
    ["kotlin"],
    ["ktlint"],
    [".editorconfig", "build.gradle.kts"],
    [".kt", ".kts"],
    ["ktlint", "-F", "{file}"],
    "https://pinterest.github.io/ktlint/",
  ),
  recipe(
    "rubocop-format",
    ["ruby"],
    ["rubocop"],
    [".rubocop.yml", "Gemfile"],
    [".rb", ".rake"],
    ["rubocop", "-A", "{file}"],
    "https://docs.rubocop.org/",
  ),
  recipe(
    "pint",
    ["php"],
    ["pint"],
    ["pint.json", "composer.json"],
    [".php"],
    ["pint", "{file}"],
    "https://laravel.com/docs/pint",
  ),
  recipe(
    "swift-format",
    ["swift"],
    ["swift-format"],
    [".swift-format", "Package.swift"],
    [".swift"],
    ["swift-format", "format", "--in-place", "{file}"],
    "https://github.com/swiftlang/swift-format",
  ),
  recipe(
    "stylua",
    ["lua"],
    ["stylua"],
    ["stylua.toml", ".stylua.toml"],
    [".lua"],
    ["stylua", "{file}"],
    "https://github.com/JohnnyMorganz/StyLua",
  ),
  recipe(
    "shfmt",
    ["shell"],
    ["shfmt"],
    [".editorconfig"],
    [".sh", ".bash", ".zsh"],
    ["shfmt", "-w", "{file}"],
    "https://github.com/mvdan/sh",
  ),
  recipe(
    "taplo",
    ["toml"],
    ["taplo"],
    ["taplo.toml"],
    [".toml"],
    ["taplo", "format", "{file}"],
    "https://taplo.tamasfe.dev/",
  ),
  recipe(
    "sqlfluff-format",
    ["sql"],
    ["sqlfluff"],
    [".sqlfluff", "pyproject.toml"],
    [".sql"],
    ["sqlfluff", "format", "{file}"],
    "https://docs.sqlfluff.com/",
  ),
  recipe(
    "terraform-fmt",
    ["terraform"],
    ["terraform"],
    [".terraform.lock.hcl"],
    [".tf", ".tfvars"],
    ["terraform", "fmt", "{file}"],
    "https://developer.hashicorp.com/terraform/cli/commands/fmt",
  ),
  recipe(
    "cmake-format",
    ["cmake"],
    ["cmake-format"],
    [".cmake-format.py", "CMakeLists.txt"],
    [".cmake"],
    ["cmake-format", "-i", "{file}"],
    "https://cmake-format.readthedocs.io/",
  ),
  recipe(
    "xmlformat",
    ["xml"],
    ["xmlformat"],
    [".xmlformat.conf"],
    [".xml", ".xsd", ".xsl"],
    ["xmlformat", "--overwrite", "{file}"],
    "https://github.com/pamoller/xmlformatter",
  ),
  recipe(
    "dockfmt",
    ["dockerfile"],
    ["dockfmt"],
    ["Dockerfile"],
    ["*"],
    ["dockfmt", "fmt", "{file}"],
    "https://github.com/jessfraz/dockfmt",
  ),
];

function recipe(
  id: string,
  languages: readonly string[],
  executables: readonly string[],
  configFiles: readonly string[],
  extensions: readonly string[],
  command: readonly string[],
  documentation: string,
  dependencies?: readonly string[],
): ToolRecipe {
  return {
    id,
    name: id,
    kind: "formatter",
    languages,
    executables,
    configFiles,
    documentation,
    ...(dependencies && { dependencies }),
    formatter: { extensions, run: { command }, output: "in-place" },
  };
}
